Add Identflats
TopoToolbox/pytopotoolbox pull request #24
Opened 2024-05-17 14:23 UTC by Teschl

Implements `identflats` for the `GridObject`. Do be able to use this function efficiently when creating the `FlowObject` I added an argument `raw` to just return the `ndarray`.

Since there is no way of making a function private in python, I think it's important to still add a function that returns multiple `GridObjects`. By using the `output` argument, the number of returned dems can be changed.

- `flats, sills = dem.identifyflats(output=['flats', 'sills'])` (default)
- `flats = dem.identifyflats(output=['flats'])`
- `sills = dem.identifyflats(output=['sills'])`

![image](https://github.com/TopoToolbox/pytopotoolbox/assets/69400012/9e2a4ead-bb5f-4295-8c11-2681ecfa0402)

When using `dem.identifyflats(raw=True)` instead of multiple `GridObject` the return will be an int32_t `nd.ndarray`.  This also contains presills.

![image](https://github.com/TopoToolbox/pytopotoolbox/assets/69400012/f58d87f3-c082-459c-b300-849a38ce0f61)

2024-05-23 13:54 UTC, wkearn requested changes
This looks pretty good! I think having different return types for external and internal use is a good idea for now.

There is one problem with the documentation for `identifyflats`.

You also need to merge/rebase the latest changes to `main`: the comments introduced by #23 to `grid.cpp` are causing a merge conflict.

2024-05-23 13:54 UTC, wkearn commented on src/topotoolbox/gridmixins/identifyflats.py
> +            Flats are identified as 1s, sills as 2s and presills as 3s in the output grid.
Presills are labeled as 5 in the output grid ( 5 = 0b001 | 0b100 ) so they show up as both flats and presills.

2024-05-24 10:07 UTC, Teschl commented
Adjusted the documentation and resolved the merge conflict, should be ready to be merged now. @wkearn

2024-05-24 10:53 UTC, wkearn approved these changes

2024-05-24 10:53 UTC, merged